[project]
name = "veridiledger"
description = "A transparent Carbon Credit Tracking platform on the Stacks ecosystem"
authors = ["VeridiLedger Team"]
telemetry = false
cache_dir = ".clarinet"
requirements = []
boot_contracts = []

[contracts.carbon-credit-tracker]
path = "contracts/carbon-credit-tracker.clar"
clarity_version = 2
epoch = "2.4"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
